### ISSUE TITLE
custom_settings_page_setup  does not work in functions.php

### ISSUE THREAD

**Issue by eugeneegbe** [taniarascia/startwordpress#2]
The side bar URLs for gitbub and twitter are registered in functions.php but when i tried registering that for facebook it didn't work same as it was done for the previous two

**Comment by eugeneegbe** [comment]
that was addressed in this  [Pull request](https://github.com/taniarascia/startwordpress/pull/1/commits/cc93f876f6913648a853cbee05ff3e66caee89e7)

**Comment by taniarascia** [comment]
All fixed, sorry for the confusion.
